### ISSUE TITLE
Positive and negative lookbehind doesnt work with \b anchors

### ISSUE THREAD

**Issue by graceful-potato** [microsoft/vscode-textmate#121]
\b anchor crashes the whole language file if it is inside lookbehind. It works fine in textmate so i think it is a bug. Tested on a brand new vscode extension created with yo.

\b works fine inside lookahead
![Screenshot from 2019-12-12 02-20-58](https://user-images.githubusercontent.com/56965223/70669811-7e668780-1c88-11ea-942c-1c61b10b93a6.png)

but as soon as you add \b in any lookbehind, syntax highlight crashes and "Inspect TM Scopes" stop loading
![Screenshot from 2019-12-12 02-20-33](https://user-images.githubusercontent.com/56965223/70670613-917a5700-1c8a-11ea-8aec-594bb37eb47c.png)

**Comment by msftrncs** [comment]
I had assumed `\b` was not permitted in LookBehind.  I believe you will find an error in the log (or if you do a debug).

However, other regex engines seem to tolerate it and work as expected.

Yet, it must be pretty rare to use `\b` in LookBehind in TextMate, since this isn't being reported everyday.  I have been using a work-around which is much more complicated, since I had assumed it was a regex limitation.

And yet, however, LookBehind's in TextMate are troublesome anyway!  What is behind you is not always what it seems.  Its best to make decisions based on what is in front.   This is probably why this hasn't been reported.

**Comment by graceful-potato** [comment]
@msftrncs 
Yes, you are right i found an error in the developers tools
```
  ERR invalid pattern in look-behind: Error: invalid pattern in look-behind
    at Object.createOnigScanner (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:67:24)
    at Grammar.createOnigScanner (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2578:30)
    at RegExpSourceList.compile (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:1875:38)
    at IncludeOnlyRule.compile (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:1974:45)
    at matchRule (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2822:28)
    at matchRuleOrInjections (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2841:23)
    at scanNext (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2937:17)
    at _tokenizeString (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2930:9)
    at Grammar._tokenize (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2680:25)
    at Grammar.tokenizeLine2 (/snap/code/22/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:2650:22)
    at k.tokenize2 (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4755:768)
    at D.tokenize2 (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4755:309)
    at m (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1336:590)
    at p._updateTokensUntilLine (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1335:492)
    at p._tokenizeOneInvalidLine (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1335:145)
    at p._revalidateTokensNow (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1334:226)
    at Immediate._onImmediate (file:///snap/code/22/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1334:24)
    at processImmediate (internal/timers.js:439:21)
```
Can i ask you what work-around did you use for this issue?

**Comment by msftrncs** [comment]
I used `\W`, but that requires an alternative, because `\W` cannot match where there is not a character, so I have used:

``` JSON
"comment": "in look behind, '\\WX|^X' is equivalent to '\\bX' that cannot be used in look behinds",
"match": "(?<=\\Whello|^hello)\\s+world\\b"
```

The reason that `\b` might not be allowed in lookbehind is because Ruby's regex doesn't allow for variable length lookbehinds.  Myself, I don't consider `\b` to require a variable length, but its probably the fancy work that it can allow `^` to also match, and that is not a character, it is a position.  TextMate might be using a newer version of regex that can at least allow `\b` in lookbehind, or they have provided an alternate workaround.

**Comment by graceful-potato** [comment]
@msftrncs
First of all thanks for the example of workaround!
Just checked and find out that textmate uses onigmo (its a fork of oniguruma), but vscode uses port of oniguruma.

I just installed old version of ruby with oniguruma, and got the same error
```ruby
1.9.3-p551 :001 > regex = /(?<=\bhello\b )world/
SyntaxError: (irb):1: invalid pattern in look-behind: /(?<=\bhello\b )world/
```
Looks like only onigmo supports \b in lookbehind and thats why we have different behaviour in vscode.
I find it a bit odd that vscode-textamte uses another lib for regular expressions.

**Comment by msftrncs** [comment]
The use of different varieties of the Oniguruma library is due to architecture, TextMate is not tied to JavaScript/Node/Electron/Chrome, where as both Atom and VSCode-TextMate is, so Atom and VSCode-TextMate both use [Node-Oniguruma](https://github.com/atom/node-oniguruma).

It looks like some of the Onigmo improvements have also been implemented in recent Oniguruma, but not in Node-Oniguruma.  It is in Node-Oniguruma that the problem for Atom and VSCode-TextMate differing from TextMate seems to be.

**Comment by msftrncs** [comment]
@graceful-potato, do you have a reference for Origumo supporting `\b` in lookbehind?

All Origuruma variants seem to be the same regarding the requirement that a match in a lookbehind must match a fixed length.  If we use the definition that `\b` is actually short for `(?<=\W|^)(?=\w)|(?<=\w)(?=\W|$)`, I can see why initially it would be unsupported, but ideally `\b` is just an anchor and shouldn't be considered to have any length, and that probably why its supported probably via a distinct exception.  I'm going to guess, that the Onigmo regex compiler handles the `\b` in a lookbehind by using a in-lookbehind specific compilation rather than the general version I mentioned earlier.

Ideally, `\b` should always be compiled for the specific application.  `\bhello` should be compiled to `(?<=\W|^)hello` and `(?<=\bhello)` should be compiled as `(?<=\Whello|^hello)` (which is why that is the work-around).  `hello\b` -> `hello(?=\W|$)` and `(?<=hello\b)` -> `(?<=hello)(?=\W|$)`, and in the example you gave, `(?<=\bhello\b )` -> `(?<=\Whello |^hello )` (the second `\b` is simplified out).

**Comment by graceful-potato** [comment]
@msftrncs yes, i found [this](https://github.com/k-takata/Onigmo/blob/0830382895a303a478de988b7ba7af0f0e86bb6c/regcomp.c#L4137)

**Comment by msftrncs** [comment]
@graceful-potato, thanks, that is a great reference.  The blame for that line is 8 years old, and the commit was specifically adding support for `\b` and `\B` in look behind.  

Unfortunately the same file in Node-Oniguruma is way behind.... [here](https://github.com/atom/node-oniguruma/blob/eba5efc24594ebc29b9d96bd5360b3897231b050/deps/onig/regcomp.c#L3861-L3862)   I am not sure why its so far behind.

I am sure @alexdima will agree, this issue probably needs to be moved to Node-Oniguruma.

**Comment by graceful-potato** [comment]
@msftrncs and i found [commit](https://github.com/kkos/oniguruma/commit/3bac736cce371463bbd0b7bdb9466bba9ee59dc4) to oniguruma which implements same thing but its 3yo, not 8. So basically this feature is supported even in oniguruma at this moment.

**Comment by alexdima** [comment]
We are using https://github.com/atom/node-oniguruma , and they are on an old oniguruma version.

**Comment by jeff-hykin** [comment]
> Yet, it must be pretty rare to use `\b` in LookBehind in TextMate, since this isn't being reported everyday

I've definitely run into it, I just didn't realize it was bug and not a limitation. It would be pretty useful to have though, I've also had to come up with some creative workarounds.

**Comment by msftrncs** [comment]
@graceful-potato, @jeff-hykin, I think this issue might be able to be closed.

@alexdima, it seems that a newer version of Oniguruma is now being used, and support for `\b` in lookarounds is now working correctly.  I think I read in another issue (maybe on Atom) that the difference in versions was causing other issues as well and there was a drive to get Node-Oniguruma up to date?

I also notice that variable length lookbehinds seem to be supported now, at least compound different length alternation.

```JSON
"end": "(?<=\\bEND_(?:VAR|PROGRAM|INTERFACE|FUNCTION_BLOCK|FUNCTION|METHOD|PROPERTY))\\b",
```

**Comment by alexdima** [comment]
Yes, that's correct, we now use `vscode-oniguruma` which contains a very recent `oniguruma` version.
