### ISSUE TITLE
Tokenizer fails when line is empty / newlines

### ISSUE THREAD

**Issue by felixsanz** [Microsoft/vscode-textmate#15]
I don't know if i'm doing it correctly, but i'm actually doing:

```javascript
let ruleStack
const tokens = snippet.split('\n').reduce((tokenList, line) => {
   const r = grammar.tokenizeLine(line, ruleStack)
   ruleStack = r.ruleStack
```

So basically i split the piece of code by new line characters and tokenize line by line. The problem is that some lines contain just new line characters, for example an empty line that separate 2 lines of code like this:

```javascript
var foo
// <--- this line contains just \n
var bar
```

But since i'm splitting the new line characters to parse line by line, that line contains nothing now.

But the tokenizer still generates this:

```
{ tokens: [ { startIndex: 0, endIndex: 1, scopes: [Object] } ],
  ruleStack: 
   [ StackElement {
       ruleId: 1,
       enterPos: -1,
       endRule: null,
       scopeName: 'source.js',
       contentName: null,
       whileRule: null } ] }
```

startIndex 0 is ok, but why endIndex is 1 and not 0? Looks like there is a character but there is none.

If you add `line.charCodeAt(0)` you get NaN because there is nothing there. the same with `line.slice(0, 1)`

**Comment by alexandrudima** [comment]
While tokenizing a line, a `\n` is added to it because regexes in textmate grammars sometimes do target the `\n` character.

It is even possible for them to push/pop states after the `\n` character.

I thought it would be useful to be able to observe from the outside what the grammar does around those `\n` characters, hence the last returned token will have an `endIndex` of `lineLength + 1`.

I can remove this behaviour or put it behind a flag, but it does reflect what the grammar does (e.g. consider you were a grammar author and you'd wanna know exactly what your grammar does).

**Comment by felixsanz** [comment]
@alexandrudima if its intended i'm ok with it. it was just weird. feel free to close the issue if you consider, or leave it open if you are going to implement a change, but for me there is no issue anymore as i now know it

**Comment by alexandrudima** [comment]
Given more thought, I prefer to leave the current behaviour in, the last `endIndex` is `lineLength + 1`.
