### ISSUE TITLE
oniguruma and onigasm should be listed as peerDependencies

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-textmate#79]
It's possible to use `vscode-textmate` with `onigasm`, but now installing `vscode-textmate` will always download & compile a copy of `oniguruma`. So I think both should be marked as `peerDependencies`.

**Comment by NeekSandhu** [comment]
😲 YOU READ MY MIND!!!

I was about to create an issue with the exact same title. This issue is the very reason I'm having to maintain `monaco-textmate`. Due to the way `vscode-textmate` hooks with `oniguruma` and carries it wherever it goes, I cannot bundle it with webapps.

I'd really want `vscode-textmate` as "source-of-truth" and not want `monaco-textmate` to lag behind in terms of features/patches.

**Comment by octref** [comment]
@NeekSandhu I read your source code too :p

**Comment by NeekSandhu** [comment]
cc @alexandrudima @aeschli

**Comment by octref** [comment]
Seems fixed already. Thanks @alexdima 👍
