### ISSUE TITLE
Remove recovery logic and fix wrong syntax

### ISSUE THREAD

**Issue by omochi** [Microsoft/vscode-textmate#84]
Hi, I found this recovery logic.

https://github.com/Microsoft/vscode-textmate/blob/6b4f4d7bfde2c1baaf8b25906657fd6d5075a6a3/src/utils.ts#L71-L74

This is need for first-mate test case `#53`.

https://github.com/Microsoft/vscode-textmate/blob/6b4f4d7bfde2c1baaf8b25906657fd6d5075a6a3/test-cases/first-mate/fixtures/makefile.json#L294-L299

But I think this recovery logic is unnecessary.
Instead, fix wrong syntax definition to:

```
						{
							"captures": {
								"1": {
									"name": "support.function.target.$2.makefile"
								}
							},
							"match": "^\\s*(\\.(PHONY|SUFFIXES|DEFAULT|PRECIOUS|INTERMEDIATE|SECONDARY|SECONDEXPANSION|DELETE_ON_ERROR|IGNORE|LOW_RESOLUTION_TIME|SILENT|EXPORT_ALL_VARIABLES|NOTPARALLEL|ONESHELL|POSIX))\\s*$"
						},
```

Its just only change `$1` to `$2`.

How do you think?

**Comment by msftrncs** [comment]
FYI, since the syntax files are shared by other editors, it may not be possible to convince all grammar file owners to change, when all the other editors (possibly) handle this the same as VS Code-TextMate.  Properly escaping potentially unwanted characters is always a good idea, and its possible that this doesn't go as far as it should to make sure the replacement complies with the guidelines of scope names.

**Comment by omochi** [comment]
ok, thanks to comment.
